-------------------------PROFIT GENERATED-------------------------
select (sum(RIDE_CHARGES.ride_amount)-sum(electricity_cal.cost)) as REVENUE_GENERATED from electricity_cal,ride_charges;


-------------------------COUNT OF TYPE OF USERS-------------------------
SELECT SUM(CASE WHEN user_type = 'REGULAR' THEN 1 ELSE 0 END) AS "REGULAR USERS", 
SUM(CASE WHEN user_type = 'PREMIUM' THEN 1 ELSE 0 END) AS "PREMIUM USERS" 
FROM user_type_view; 

-------------------------REVENUE GENERATED BY RIDES-------------------------
select sum(ride_amount) as "RIDE REVENUE GENERATED" from RIDE_CHARGES; 

